# Generated by Django 6.0.6 on 2026-06-04 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=5)),
                ('mobile_number', models.CharField(db_index=True, max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('consulting_doctor_name', models.CharField(blank=True, default='', max_length=255)),
                ('chief_complaint', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'mobile_number'], name='patients_pa_clinic__cbf1b3_idx'), models.Index(fields=['clinic', 'full_name'], name='patients_pa_clinic__f1cf8d_idx'), models.Index(fields=['created_date'], name='patients_pa_created_a9f64e_idx')],
            },
        ),
    ]
