# Generated by Django 6.0.6 on 2026-06-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
