# Generated by Django 6.0.6 on 2026-06-16 23:15

from django.db import migrations
import re

def backfill_patient_ids(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    Clinic = apps.get_model('clinics', 'Clinic')
    
    for clinic in Clinic.objects.all():
        # Get all patients for this clinic (including soft-deleted ones)
        # Since standard Django ORM filter applies, we query all matching rows
        patients = Patient.objects.filter(clinic=clinic).order_by('created_at')
        
        next_num = 1
        for patient in patients:
            if not patient.patient_id:
                patient.patient_id = f"PAT-{next_num:04d}"
                patient.save(update_fields=['patient_id'])
                next_num += 1
            else:
                # If they already have an ID, parse it to maintain sequence continuity
                match = re.search(r'\d+', patient.patient_id)
                if match:
                    next_num = max(next_num, int(match.group()) + 1)

class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_patient_id'),
    ]

    operations = [
        migrations.RunPython(backfill_patient_ids, reverse_code=migrations.RunPython.noop),
    ]
