# Generated by Django 6.0.6 on 2026-06-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CLINIC_OWNER', 'Clinic Owner')], db_index=True, default='CLINIC_OWNER', max_length=20),
        ),
    ]
