# Generated by Django 6.0.6 on 2026-06-04 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_type', models.CharField(choices=[('PATIENT', 'Patient'), ('CLINIC', 'Clinic')], default='PATIENT', max_length=20)),
                ('recipient_value', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('sent', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('PATIENT_SAME_DAY', 'Patient Same Day Reminder'), ('CLINIC_PREV_DAY', 'Clinic Previous Day Summary'), ('CLINIC_SAME_DAY', 'Clinic Same Day Summary')], db_index=True, max_length=30)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['clinic', 'sent'], name='notificatio_clinic__a35794_idx'), models.Index(fields=['scheduled_for', 'sent'], name='notificatio_schedul_4f2daa_idx')],
            },
        ),
    ]
