# Generated by Django 6.0.6 on 2026-06-14 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_notification_whatsapp_number'),
        ('notifications', '0005_fix_production_whatsapp_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reminderhistory',
            new_name='notificatio_clinic__450c9d_idx',
            old_name='notif_remhist_clinic_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reminderhistory',
            new_name='notificatio_schedul_392907_idx',
            old_name='notif_remhist_scheduled_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reminderhistory',
            new_name='notificatio_appoint_52ad6e_idx',
            old_name='notif_remhist_appt_slot_idx',
        ),
        migrations.AlterField(
            model_name='reminderhistory',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='reminderhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whatsappsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
