# Generated by Django 6.0.6 on 2026-08-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_rename_notif_remhist_clinic_status_idx_notificatio_clinic__450c9d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('PATIENT_REMINDER_3HR', 'Patient 3-Hour Reminder'), ('CLINIC_TOMORROW_SUMMARY', 'Clinic Tomorrow Summary (7 PM IST)'), ('PATIENT_SAME_DAY', 'Patient Same Day Reminder'), ('CLINIC_PREV_DAY', 'Clinic Previous Day Summary'), ('CLINIC_SAME_DAY', 'Clinic Same Day Summary')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_type',
            field=models.CharField(choices=[('PATIENT_REMINDER_3HR', 'Patient 3-Hour Reminder'), ('CLINIC_TOMORROW_SUMMARY', 'Clinic Tomorrow Summary (7 PM IST)'), ('PATIENT_SAME_DAY', 'Patient Same Day Reminder'), ('CLINIC_PREV_DAY', 'Clinic Previous Day Summary'), ('CLINIC_SAME_DAY', 'Clinic Same Day Summary')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='reminderhistory',
            name='slot',
            field=models.CharField(choices=[('3_HOURS_BEFORE', '3 Hours Before Appointment'), ('DAY_BEFORE', 'Evening before appointment (7 PM IST)'), ('SAME_DAY', 'Morning of appointment (7 AM IST)')], db_index=True, max_length=15),
        ),
    ]
