# Generated by Django 6.0.6 on 2026-06-04 08:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('consulting_doctor', models.CharField(max_length=255)),
                ('diagnosis', models.TextField()),
                ('treatment_given', models.TextField()),
                ('prescription_notes', models.TextField(blank=True, default='')),
                ('general_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
                'indexes': [models.Index(fields=['clinic', 'patient'], name='visits_visi_clinic__a9a0d5_idx'), models.Index(fields=['visit_date'], name='visits_visi_visit_d_61b894_idx')],
            },
        ),
    ]
