# Generated by Django 6.0.6 on 2026-06-14 13:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_notification_whatsapp_number'),
        ('patients', '0004_remove_patient_user'),
        ('visits', '0002_visit_deleted_at_visit_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bill_number', models.CharField(db_index=True, max_length=50)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('doctor_name', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=20)),
                ('clinic_address', models.TextField(blank=True, default='')),
                ('clinic_contact', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='patients.patient')),
            ],
            options={
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('CARD', 'Card'), ('NET_BANKING', 'Net Banking'), ('OTHER', 'Other')], default='UPI', max_length=50)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='visits.bill')),
            ],
        ),
        migrations.CreateModel(
            name='BillTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=255)),
                ('treatment_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='visits.bill')),
            ],
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['clinic', 'patient'], name='visits_bill_clinic__ccee05_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_date'], name='visits_bill_bill_da_bc20f3_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['is_deleted'], name='visits_bill_is_dele_dc845d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('clinic', 'bill_number')},
        ),
    ]
