# Generated by Django 6.0.6 on 2026-06-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionevent',
            name='razorpay_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clinicsubscription',
            name='grace_period_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicsubscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['razorpay_event_id'], name='subscriptio_razorpa_0098b9_idx'),
        ),
    ]
