# Generated by Django 6.0.6 on 2026-06-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='notification_whatsapp_number',
            field=models.CharField(blank=True, help_text="Clinic's destination mobile number for summaries.", max_length=30, null=True),
        ),
    ]
