# Generated by Django 6.0.6 on 2026-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_notification_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
